;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.

;; RUN: wasm-opt %s -all -o %t.text.wast -g -S
;; RUN: wasm-as %s -all -g -o %t.wasm
;; RUN: wasm-dis %t.wasm -all -o %t.bin.wast
;; RUN: wasm-as %s -all -o %t.nodebug.wasm
;; RUN: wasm-dis %t.nodebug.wasm -all -o %t.bin.nodebug.wast
;; RUN: cat %t.text.wast | filecheck %s --check-prefix=CHECK-TEXT
;; RUN: cat %t.bin.wast | filecheck %s --check-prefix=CHECK-BIN
;; RUN: cat %t.bin.nodebug.wast | filecheck %s --check-prefix=CHECK-BIN-NODEBUG

(module
  ;; CHECK-TEXT:      (type $ht (handler i32))
  ;; CHECK-BIN:      (type $ht (handler i32))
  (type $ht (handler i32))

  (func (export "main") (param (ref $ht))
    (unreachable))
)
;; CHECK-TEXT:      (type $1 (func (param (ref $ht))))

;; CHECK-TEXT:      (export "main" (func $0))

;; CHECK-TEXT:      (func $0 (type $1) (param $0 (ref $ht))
;; CHECK-TEXT-NEXT:  (unreachable)
;; CHECK-TEXT-NEXT: )

;; CHECK-BIN:      (type $1 (func (param (ref $ht))))

;; CHECK-BIN:      (export "main" (func $0))

;; CHECK-BIN:      (func $0 (type $1) (param $0 (ref $ht))
;; CHECK-BIN-NEXT:  (unreachable)
;; CHECK-BIN-NEXT: )

;; CHECK-BIN-NODEBUG:      (type $0 (handler i32))

;; CHECK-BIN-NODEBUG:      (type $1 (func (param (ref $0))))

;; CHECK-BIN-NODEBUG:      (export "main" (func $0))

;; CHECK-BIN-NODEBUG:      (func $0 (type $1) (param $0 (ref $0))
;; CHECK-BIN-NODEBUG-NEXT:  (unreachable)
;; CHECK-BIN-NODEBUG-NEXT: )
