;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.

;; RUN: wasm-opt %s -all -o %t.text.wast -g -S
;; RUN: wasm-as %s -all -g -o %t.wasm
;; RUN: wasm-dis %t.wasm -all -o %t.bin.wast
;; RUN: wasm-as %s -all -o %t.nodebug.wasm
;; RUN: wasm-dis %t.nodebug.wasm -all -o %t.bin.nodebug.wast
;; RUN: cat %t.text.wast | filecheck %s --check-prefix=CHECK-TEXT
;; RUN: cat %t.bin.wast | filecheck %s --check-prefix=CHECK-BIN
;; RUN: cat %t.bin.nodebug.wast | filecheck %s --check-prefix=CHECK-BIN-NODEBUG

(module
  ;; CHECK-TEXT:      (type $ht-1 (handler i32))
  ;; CHECK-BIN:      (type $ht-1 (handler i32))
  (type $ht-1 (handler (result i32)))
  ;; CHECK-TEXT:      (type $ht-2 (handler))
  ;; CHECK-BIN:      (type $ht-2 (handler))
  (type $ht-2 (handler))

  (func (export "main-1") (param (ref $ht-1))
    (unreachable))
  (func (export "main=2") (param (ref $ht-2))
    (unreachable))
)
;; CHECK-TEXT:      (type $2 (func (param (ref $ht-1))))

;; CHECK-TEXT:      (type $3 (func (param (ref $ht-2))))

;; CHECK-TEXT:      (export "main-1" (func $0))

;; CHECK-TEXT:      (export "main=2" (func $1))

;; CHECK-TEXT:      (func $0 (type $2) (param $0 (ref $ht-1))
;; CHECK-TEXT-NEXT:  (unreachable)
;; CHECK-TEXT-NEXT: )

;; CHECK-TEXT:      (func $1 (type $3) (param $0 (ref $ht-2))
;; CHECK-TEXT-NEXT:  (unreachable)
;; CHECK-TEXT-NEXT: )

;; CHECK-BIN:      (type $2 (func (param (ref $ht-1))))

;; CHECK-BIN:      (type $3 (func (param (ref $ht-2))))

;; CHECK-BIN:      (export "main-1" (func $0))

;; CHECK-BIN:      (export "main=2" (func $1))

;; CHECK-BIN:      (func $0 (type $2) (param $0 (ref $ht-1))
;; CHECK-BIN-NEXT:  (unreachable)
;; CHECK-BIN-NEXT: )

;; CHECK-BIN:      (func $1 (type $3) (param $0 (ref $ht-2))
;; CHECK-BIN-NEXT:  (unreachable)
;; CHECK-BIN-NEXT: )

;; CHECK-BIN-NODEBUG:      (type $0 (handler i32))

;; CHECK-BIN-NODEBUG:      (type $1 (handler))

;; CHECK-BIN-NODEBUG:      (type $2 (func (param (ref $0))))

;; CHECK-BIN-NODEBUG:      (type $3 (func (param (ref $1))))

;; CHECK-BIN-NODEBUG:      (export "main-1" (func $0))

;; CHECK-BIN-NODEBUG:      (export "main=2" (func $1))

;; CHECK-BIN-NODEBUG:      (func $0 (type $2) (param $0 (ref $0))
;; CHECK-BIN-NODEBUG-NEXT:  (unreachable)
;; CHECK-BIN-NODEBUG-NEXT: )

;; CHECK-BIN-NODEBUG:      (func $1 (type $3) (param $0 (ref $1))
;; CHECK-BIN-NODEBUG-NEXT:  (unreachable)
;; CHECK-BIN-NODEBUG-NEXT: )
